# Generated by Django 3.2.12 on 2022-03-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
        ),
    ]
