# Generated by Django 3.2.12 on 2022-03-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('profiles', '0002_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='Tag',
        ),
    ]
