# Generated by Django 3.2.12 on 2022-04-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_tag_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
