# Generated by Django 3.2.12 on 2022-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
