# Generated by Django 3.2.12 on 2022-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], decimal_places=2, max_digits=3),
        ),
    ]
