# Generated by Django 3.2.12 on 2022-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_entry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_started',
            field=models.DateField(null=True),
        ),
    ]
