# Generated by Django 3.2.12 on 2022-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('actors', models.CharField(blank=True, max_length=200)),
                ('published', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('reader', models.CharField(blank=True, max_length=100)),
                ('media_type', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIBLE', 'Audible')], max_length=10)),
                ('audience', models.CharField(blank=True, max_length=30)),
                ('promo_img', models.ImageField(blank=True, upload_to='')),
                ('promo_desc', models.TextField(blank=True, max_length=10000)),
                ('author_link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
