# Generated by Django 3.2.12 on 2022-03-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_tag_media'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ManyToManyField(to='media.Media')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.tag')),
            ],
        ),
    ]
