# Generated by Django 3.2.12 on 2022-04-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20220421_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagged',
        ),
    ]
