# Generated by Django 3.2.12 on 2022-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_tagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
