# Generated by Django 3.2.12 on 2022-05-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_tag_user'),
        ('media', '0007_auto_20220504_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagged',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
        migrations.AlterField(
            model_name='tagged',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.tag'),
        ),
    ]
