# Generated by Django 3.2.12 on 2022-05-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20220504_0511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagged',
        ),
    ]
