# Generated by Django 3.2.12 on 2022-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_delete_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ave_rating',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], decimal_places=2, default=2, max_digits=3),
            preserve_default=False,
        ),
    ]
