# Generated by Django 3.2.12 on 2022-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_ave_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
