# Generated by Django 3.2.12 on 2022-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_media_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='published',
            field=models.IntegerField(null=True),
        ),
    ]
