# Generated by Django 3.2.12 on 2022-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_alter_media_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
