# Generated by Django 3.2.12 on 2022-05-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_alter_media_ave_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author_link',
            field=models.URLField(blank=True, default='google.com', null=True),
        ),
    ]
