# Generated by Django 3.2.12 on 2022-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_alter_media_author_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author_link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
    ]
