# Generated by Django 3.2.13 on 2022-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_alter_media_author_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='ave_rating',
            field=models.DecimalField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
